
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connector101314 < Formula
  desc "Manage content in multi platforms."
  homepage "https://github.com/SplashtopInc/homebrew-workspace"
  version "1.0.13-14"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://ssw-artifacts.s3.us-west-2.amazonaws.com/connector/prod/darwin/arm64/connector-arm64-1.0.13-14"
      sha256 "c9cf3ca34dc766c67883ad1fcf30b3a7179b6e01e80d0554cc102db747d2cb12"

      def install
        bin.install Dir["*"].first => "connector"
      end
    end
    if Hardware::CPU.intel?
      url "https://ssw-artifacts.s3.us-west-2.amazonaws.com/connector/prod/darwin/amd64/connector-amd64-1.0.13-14"
      sha256 "b6620eab5ff9db3b717b5361f53c27a2c7037472cf9bc7f57f52b0f8882e4ced"

      def install
        bin.install Dir["*"].first => "connector"
      end
    end
  end

  test do
    system "#{bin}/connector -h"
  end
end

