
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connector < Formula
  desc "Manage content in multi platforms."
  homepage "https://github.com/SplashtopInc/homebrew-workspace"
  version "0.0.3.035.3"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://s3.us-west-2.amazonaws.com/splashlock-assets.splashshield.ai/connector/stage/darwin/arm64/connector-arm64-stage-0.0.3.035.3"
      sha256 "501dbde38717e4c82e65a212dde94c083fd7566514995483805bd7ce0806229e"

      def install
        bin.install Dir["*"].first => "connector"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/connector", "-h")
        (bash_completion/"connector").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/connector", "-h")
        (zsh_completion/"_connector").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://s3.us-west-2.amazonaws.com/splashlock-assets.splashshield.ai/connector/stage/darwin/amd64/connector-amd64-stage-0.0.3.035.3"
      sha256 "0c01ccba0c0f0365f67448097d182fb0b8a56b1b8c5a518eac7a9745b149a214"

      def install
        bin.install Dir["*"].first => "connector"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/connector", "-h")
        (bash_completion/"connector").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/connector", "-h")
        (zsh_completion/"_connector").write output
      end
    end
  end

  test do
    system "#{bin}/connector -h"
  end
end

