
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connector003034 < Formula
  desc "Manage content in multi platforms."
  homepage "https://github.com/SplashtopInc/homebrew-workspace"
  version "0.0.3.034"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://s3.us-west-2.amazonaws.com/splashlock-assets.splashshield.ai/connector/stage/arm64/connector-arm64-stage-0.0.3.034"
      sha256 "0cae4791d19827a9268b1b837c9d1eb220c968e100ade0884245adfc78f20463"

      def install
        bin.install Dir["*"].first => "connector"
        # Install bash completion
        #output = Utils.safe_popen_read("#{bin}/connector", "-h")
        #(bash_completion/"connector").write output
        # Install zsh completion
        #output = Utils.safe_popen_read("#{bin}/connector", "-h")
        #(zsh_completion/"_connector").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://s3.us-west-2.amazonaws.com/splashlock-assets.splashshield.ai/connector/stage/amd64/connector-amd64-stage-0.0.3.034"
      sha256 "adb9b7eff6493ee3c377afa1b9f31a97c10b7947b0d2f336f7a6b4ef04d44708"

      def install
        bin.install Dir["*"].first => "connector"
        # Install bash completion
        #output = Utils.safe_popen_read("#{bin}/connector", "-h")
        #(bash_completion/"connector").write output
        # Install zsh completion
        #output = Utils.safe_popen_read("#{bin}/connector", "-h")
        #(zsh_completion/"_connector").write output
      end
    end
  end

  #test do
  #  system "#{bin}/connector -h"
  #end
end

