
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connector < Formula
  desc "Manage content in multi platforms."
  homepage "https://github.com/JacobLi11/ssw"
  version "0.1.39-stage-0.0.3.34"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://s3.us-west-2.amazonaws.com/splashlock-assets.splashshield.ai/connector/stage/arm64/connector-arm64-stage-0.0.3.035"
      sha256 "2a7f647b649856d4779f0839f1ce902859ea5ac2c395bf88efa157ce2adc26bd"

      def install
        bin.install Dir["*"].first => "connector"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/connector", "-h")
        (bash_completion/"connector").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/connector", "-h")
        (zsh_completion/"_connector").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://s3.us-west-2.amazonaws.com/splashlock-assets.splashshield.ai/sdpc/stage/darwin/amd64/sdpc-darwin-amd64-0.1.39-stage-0.0.3.34.zip"
      sha256 "bc79edb45d26ef243bd263169c78b7a81894d4e3ba95de3cc93eca40941e1ff5"

      def install
        bin.install "sdpc-darwin-amd64"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/sdpc-darwin-amd64", "-h")
        (bash_completion/"sdpc-darwin-amd64").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/sdpc-darwin-amd64", "-h")
        (zsh_completion/"_sdpc-darwin-amd64").write output
      end
    end
  end

  test do
    system "#{bin}/sdpc-darwin-arm64 -h || #{bin}/sdpc-darwin-amd64 -h"
  end
end

