
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SdpcStage01191stage10911 < Formula
  desc "Manage content in multi platforms."
  homepage "https://github.com/SplashtopInc/homebrew-workspace"
  version "0.1.191-stage-1.0.91.1"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://download.stage.ztw.splashtop.com/sdpc/stage/darwin/arm64/sdpc-darwin-arm64-0.1.191-stage-1.0.91.1.zip"
      sha256 "e0ff67deb23faf3e50c750812cd1bee8994974cd41c2d000fe7471552c67b973"

      def install
        bin.install "sdpc-darwin-arm64" => "sdpc"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/sdpc", "-h")
        (bash_completion/"sdpc").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/sdpc", "-h")
        (zsh_completion/"_sdpc").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://download.stage.ztw.splashtop.com/sdpc/stage/darwin/amd64/sdpc-darwin-amd64-0.1.191-stage-1.0.91.1.zip"
      sha256 "6ad3a38b45b7fd3ac7ef2b4b057a690ef82a061b7756c87b2f368d32d31959e5"

      def install
        bin.install "sdpc-darwin-amd64" => "sdpc"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/sdpc", "-h")
        (bash_completion/"sdpc").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/sdpc", "-h")
        (zsh_completion/"_sdpc").write output
      end
    end
  end

  test do
    system "#{bin}/sdpc -h"
  end
end

